# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.5 on 2017-02-28 22:38
=======
# Generated by Django 1.10.5 on 2017-03-01 01:01
>>>>>>> d4662b62724f4b7e538c41d38beb967d56af029d
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(default='poopyhead', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('avatar', models.ImageField(default='avatar/default/default.jpg', upload_to='login_register/avatar/')),
=======
>>>>>>> d4662b62724f4b7e538c41d38beb967d56af029d
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
