from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Schedule(models.Model):
    user = models.ForeignKey(User, related_name = 'schedule_user')
    mon = models.ForeignKey(Day, related_name = 'mon_schedule')
    tue = models.ForeignKey(Day, related_name = 'tue_schedule')
    wed = models.ForeignKey(Day, related_name = 'wed_schedule')
    thu = models.ForeignKey(Day, related_name = 'thu_schedule')
    fri = models.ForeignKey(Day, related_name = 'fri_schedule')
    sat = models.ForeignKey(Day, related_name = 'sat_schedule')
    sun = models.ForeignKey(Day, related_name = 'sun_schedule')
    mon2 = models.ForeignKey(Day, related_name = 'mon_schedule')
    tue2 = models.ForeignKey(Day, related_name = 'tue_schedule')
    wed2 = models.ForeignKey(Day, related_name = 'wed_schedule')
    thu2 = models.ForeignKey(Day, related_name = 'thu_schedule')
    fri2 = models.ForeignKey(Day, related_name = 'fri_schedule')
    sat2 = models.ForeignKey(Day, related_name = 'sat_schedule')
    sun2 = models.ForeignKey(Day, related_name = 'sun_schedule')
class Day(models.Model):
    9_10 = models.BooleanField(False)
    10_11 = models.BooleanField(False)
    11_12 = models.BooleanField(False)
    12_13 = models.BooleanField(False)
    13_14 = models.BooleanField(False)
    14_15 = models.BooleanField(False)
    15_16 = models.BooleanField(False)
    16_17 = models.BooleanField(False)
    17_18 = models.BooleanField(False)
    18_19 = models.BooleanField(False)
    19_20 = models.BooleanField(False)
    20_21 = models.BooleanField(False)
    21_22 = models.BooleanField(False)
    22_23 = models.BooleanField(False)
    23_0 = models.BooleanField(False)
    0_1 = models.BooleanField(False)
    1_2 = models.BooleanField(False)
    2_3 = models.BooleanField(False)
    3_4 = models.BooleanField(False)
    4_5 = models.BooleanField(False)
    5_6 = models.BooleanField(False)
    6_7 = models.BooleanField(False)
    7_8 = models.BooleanField(False)
    8_9 = models.BooleanField(False)
