# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='c',
            new_name='city',
        ),
    ]
