# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longtitude',
            field=models.FloatField(default=0),
        ),
    ]
