# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170301_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '250x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='image',
            name='avatar',
            field=models.ImageField(blank=True, default='login_register/avatar/default/default.jpg', upload_to='login_register/avatar/'),
        ),
    ]
