# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170228_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=False),
        ),
    ]
