# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170301_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='longtitude',
            field=models.IntegerField(default=0),
        ),
    ]
