# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('user_profile', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='this_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='match_user', to='login_register.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to='user_profile.Profile'),
        ),
    ]
