# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:03
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20170301_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, default='login_register/avatar/default/default.jpg', upload_to='login_register/avatar/'),
        ),
    ]
