# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0002_auto_20170228_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_9to10', models.BooleanField(verbose_name=False)),
                ('_10to11', models.BooleanField(verbose_name=False)),
                ('_11to12', models.BooleanField(verbose_name=False)),
                ('_12to13', models.BooleanField(verbose_name=False)),
                ('_13to14', models.BooleanField(verbose_name=False)),
                ('_14to15', models.BooleanField(verbose_name=False)),
                ('_15to16', models.BooleanField(verbose_name=False)),
                ('_16to17', models.BooleanField(verbose_name=False)),
                ('_17to18', models.BooleanField(verbose_name=False)),
                ('_18to19', models.BooleanField(verbose_name=False)),
                ('_19to20', models.BooleanField(verbose_name=False)),
                ('_20to21', models.BooleanField(verbose_name=False)),
                ('_21to22', models.BooleanField(verbose_name=False)),
                ('_22to23', models.BooleanField(verbose_name=False)),
                ('_23to0', models.BooleanField(verbose_name=False)),
                ('_0to1', models.BooleanField(verbose_name=False)),
                ('_1to2', models.BooleanField(verbose_name=False)),
                ('_2to3', models.BooleanField(verbose_name=False)),
                ('_3to4', models.BooleanField(verbose_name=False)),
                ('_4to5', models.BooleanField(verbose_name=False)),
                ('_5to6', models.BooleanField(verbose_name=False)),
                ('_6to7', models.BooleanField(verbose_name=False)),
                ('_7to8', models.BooleanField(verbose_name=False)),
                ('_8to9', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fri_schedule', to='schedules.Day')),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_schedule', to='schedules.Day')),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_schedule', to='schedules.Day')),
                ('sun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sun_schedule', to='schedules.Day')),
                ('thu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thu_schedule', to='schedules.Day')),
                ('tue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tue_schedule', to='schedules.Day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_user', to='login_register.User')),
                ('wed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wed_schedule', to='schedules.Day')),
            ],
        ),
    ]
