# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='h0to1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h10to11',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h11to12',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h12to13',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h13to14',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h14to15',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h15to16',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h16to17',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h17to18',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h18to19',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h19to20',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h1to2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h20to21',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h21to22',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h22to23',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h23to0',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h2to3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h3to4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h4to5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h5to6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h6to7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h7to8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h8to9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='h9to10',
            field=models.BooleanField(default=False),
        ),
    ]
